project:
  type: website
  output-dir: docs

website:
  title: "John Halifax"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - Education.qmd
      - CV.qmd
      - Research.qmd
      - Publications.qmd
    tools:
      - icon: github
        href: https://github.com/john-halifax
        aria-label: GitHub

format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    css: styles.css
    toc: false
    page-layout: full

editor: visual

